### ISSUE TITLE
Mixins crash in Forge version 1.18.2

### ISSUE THREAD

**Issue by Billetiado10** [feytox/FeyTweaks#13]
Minecraft: 1.18.2
Forge: 40.2.10
Mod Version: feytweaks-1.18.2-1.2.6

[crash-2023-09-08_23.23.30-client.txt](https://github.com/feytox/FeyTweaks/files/12564580/crash-2023-09-08_23.23.30-client.txt)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method getOutlineRenderJ(I)I in feytweaks.mixins.json:TextRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap feytweaks.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 29 more

**Comment by feytox** [comment]
Mixins crash = mod incompatibility.  Therefore, you should check which mod from your mod list somehow changes text rendering, turn it off and try to start the game.  If in this case the game starts normally, there are no crashes, then it is incompatible with this mod and you should write its name in the issue.

**Comment by Billetiado10** [comment]
The mod is Modern UI in the latest version. Thanks

**Comment by feytox** [comment]
The mod you specified rewrites/changes the rendering of text on signs, so it cannot be compatible with FeyTweaks.

The only thing I can recommend to you is Immediately Fast (https://modrinth.com/mod/immediatelyfast). Not sure if it will be compatible with Modern UI, but you should try it.
